### PR TITLE
Update of FRENCH translation for Custom Code extension

### PR DESCRIPTION
**Pull request by Galixte**
Hi @eeemarv @marttiphpbb,

could you merge this, please?

Regards.

### CODE REVIEW

**Comment by Galixte** [comment]
Hi @marttiphpbb,

ok I will stay in my fork. For your information I maintain more than 250 translations in French so I assume my part of job.

Sorry for the year in copyright it’s the first time that I read this rule.

**Comment by Galixte** [comment]
Hi @marttiphpbb,

I’m sorry but I don’t know why I didn’t notice that in my previous message: If you don’t want to maintain the translations, I understand. But at least remove them, because currently and for example in French, its a mix of english and french (that’s why I made this PR).

So please, add a link to my GitHub repository instead of keeping FRENCH translation out of date: https://github.com/Galixte/phpbb-ext-customcode

Regards.

**Comment by eeemarv** [comment]
Ok, good point

**Comment by marttiphpbb** [comment]
Ok, good point.

**Comment by marttiphpbb** [comment]
The translations are removed now and a link to your repo is added in version 3.1.0

**Comment by Galixte** [comment]
Thanks a lot, I’ll update the translation for 3.1.0 version.

**Pull request closed without merging**
